name: validate
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  validate:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      # download and setup butler
      - uses: ./
        name: RageAgainstThePixel/setup-butler
        with:
          api-key: ${{ secrets.BUTLER_API_KEY }}
      # run butler
      - run: butler --version
